defmodule Pinchflat.Podcasts.RssFeedBuilder do
  @moduledoc """
  Methods for building an RSS feed for a source and its media items.
  """

  @datetime_format "%a, %d %b %Y %H:%M:%S %z"

  import Pinchflat.Utils.XmlUtils, only: [safe: 1]

  alias Pinchflat.Podcasts.PodcastHelpers
  alias Pinchflat.Podcasts.DynamicFeedLinks

  @doc """
  Builds an RSS feed for a given source and its media items.
  Only MediaItems that have been persisted will be included in the feed.

  ## Options:
    - `:limit` - The maximum number of media items to include in the feed. Defaults to 2,000.
    - `:url_base` - The base URL all links are built from. Defaults to the app's own URL.
    - `:link_module` - The module that builds the feed's URLs. Defaults to
      `DynamicFeedLinks` (URLs served by Tubeless itself); the static podcast
      export passes `StaticFeedLinks` instead.
    - `:media_items` - A pre-fetched list of media items to render, bypassing
      the internal query. The static export passes the exact snapshot it linked
      to disk so the feed can't diverge from the files.

  Returns an XML document as a string.
  """
  def build(source, opts \\ []) do
    limit = Keyword.get(opts, :limit, 2_000)
    url_base = Keyword.get(opts, :url_base, PinchflatWeb.Endpoint.url())
    link_module = Keyword.get(opts, :link_module, DynamicFeedLinks)

    media_items =
      Keyword.get_lazy(opts, :media_items, fn ->
        PodcastHelpers.persisted_media_items_for(source, limit: limit)
      end)

    build_source_xml(source, media_items, url_base, link_module)
  end

  defp build_source_xml(source, media_items, url_base, link_module) do
    media_item_xml = Enum.map(media_items, &build_media_item_xml(source, &1, url_base, link_module))
    # "caching" the image path since it requires some DB calls and is used twice
    feed_image_path = link_module.feed_image_url(url_base, source, media_items)

    # Useful: resources:
    #   - https://validator.w3.org/feed/#validate_by_input
    #   - https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md
    #   - https://podba.se/validate
    """
    <?xml version="1.0" encoding="UTF-8"?>
    <rss version="2.0"
      xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd"
      xmlns:podcast="https://podcastindex.org/namespace/1.0"
      xmlns:atom="http://www.w3.org/2005/Atom">
      <channel>
        <title>#{safe(source.custom_name)}</title>
        <link>#{safe(source.original_url)}</link>
        <description>#{safe(source.description)}</description>
        <category>TV &amp; Film</category>
        <generator>Generated by Tubeless</generator>
        <language>en-us</language>
        <lastBuildDate>#{Calendar.strftime(source.updated_at, @datetime_format)}</lastBuildDate>
        <pubDate>#{Calendar.strftime(source.inserted_at, @datetime_format)}</pubDate>
        <atom:link href="#{safe(link_module.self_url(url_base, source))}" rel="self" type="application/rss+xml" />
        <podcast:locked>yes</podcast:locked>
        <podcast:guid>#{source.uuid}</podcast:guid>
        <image>
          <url>#{safe(feed_image_path)}</url>
          <title>#{safe(source.custom_name)}</title>
          <link>#{safe(source.original_url)}</link>
        </image>
        <itunes:author>#{safe(source.custom_name)}</itunes:author>
        <itunes:subtitle>#{safe(source.custom_name)}</itunes:subtitle>
        <itunes:block>yes</itunes:block>
        <itunes:image href="#{safe(feed_image_path)}"></itunes:image>
        <itunes:explicit>false</itunes:explicit>
        <itunes:category text="TV &amp; Film"></itunes:category>

        #{Enum.join(media_item_xml, "\n")}

      </channel>
    </rss>
    """
  end

  defp build_media_item_xml(source, media_item, url_base, link_module) do
    item_image_path = link_module.episode_image_url(url_base, source, media_item)

    """
    <item>
      <guid isPermaLink="false">#{media_item.uuid}</guid>
      <title>#{safe(media_item.title)}</title>
      <link>#{safe(media_item.original_url)}</link>
      <description>#{safe(media_item.description)}</description>
      <pubDate>#{Calendar.strftime(media_item.uploaded_at, @datetime_format)}</pubDate>
      <itunes:duration>#{media_item.duration_seconds}</itunes:duration>
      <enclosure
        url="#{safe(link_module.enclosure_url(url_base, source, media_item))}"
        length="#{media_item.media_size_bytes}"
        type="#{MIME.from_path(media_item.media_filepath)}"
      />
      <itunes:author>#{safe(source.custom_name)}</itunes:author>
      <itunes:subtitle>#{safe(media_item.title)}</itunes:subtitle>
      <itunes:summary><![CDATA[#{media_item.description}]]></itunes:summary>

      #{item_image_path && ~s(<itunes:image href="#{safe(item_image_path)}"></itunes:image>)}
      #{item_image_path && ~s(<podcast:images srcset="#{safe(item_image_path)}" />)}

      <itunes:explicit>false</itunes:explicit>
    </item>
    """
  end
end
